/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ca-central-1",
    "aws_cognito_identity_pool_id": "ca-central-1:dc6559ba-4c62-4333-9047-238f871805f2",
    "aws_cognito_region": "ca-central-1",
    "aws_user_pools_id": "ca-central-1_80zbdZkqO",
    "aws_user_pools_web_client_id": "4o21opuu00ihrp2ikepvhcbvb6",
    "oauth": {},
    "aws_user_files_s3_bucket": "uotfrontendbucket122756-dev",
    "aws_user_files_s3_bucket_region": "ca-central-1",
    "aws_appsync_graphqlEndpoint": "https://p6qd6wdlhvabxks7fxwj3pt7uq.appsync-api.ca-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "ca-central-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
